In [1]:
# Create a string with your name
name = "John Cena"

# Print the string
print("My Name is:", name)

My Name is: John Cena

In [2]:
# Original string
original_string = "Hello World"

# Print the original string
print("Original String:", original_string)

# Find the length of the string
string_length = len(original_string)

# Print the length of the string
print("Length of the String:", string_length)

Original String: Hello World
Length of the String: 11

In [3]:
# Original string
original_string = "Python Programming"

# Print the original string
print("Original String:", original_string)

# Slice the first 3 characters
sliced_string = original_string[:3]

# Print the sliced string
print("Sliced String:", sliced_string)

Original String: Python Programming
Sliced String: Pyt

In [4]:
# Original string
original_string = "hello"

# Print the original string
print("Original String:", original_string)

# Convert to uppercase
uppercase_string = original_string.upper()

# Print the uppercase string
print("Uppercase String:", uppercase_string)

Original String: hello
Uppercase String: HELLO

In [5]:
# Original string
original_string = "I like apple"

# Print the original string
print("Original String:", original_string)

# Replace "apple" with "orange"
new_string = original_string.replace("apple", "orange")

# Print the new string
print("New String:", new_string)

Original String: I like apple
New String: I like orange

In [32]:
# Create a list with numbers 1 to 5
my_list = [1, 2, 3, 4, 5]

# Print the list
print("My List:", my_list)

My List: [1, 2, 3, 4, 5]

In [8]:
# Create a list
my_list = [1, 2, 3, 4,5]

# Print the original list
print("Original List:", my_list)

# Append the number 10
my_list.append(10)

# Print the updated list
print("Updated List:", my_list)

Original List: [1, 2, 3, 4, 5]
Updated List: [1, 2, 3, 4, 5, 10]

In [9]:
# Create a list
my_list = [1, 2, 3, 4, 5]

# Print the original list
print("Original List:", my_list)

# Remove the number 3
my_list.remove(3)

# Print the updated list
print("Updated List:", my_list)

Original List: [1, 2, 3, 4, 5]
Updated List: [1, 2, 4, 5]

In [12]:
# Create a list
my_list = [10, 90, 30, 40, 50, 100]

# Print the original list
print("Original List:", my_list)

# Access the second element
second_element = my_list[1]

# Print the second element
print("Second Element:", second_element)

Original List: [10, 90, 30, 40, 50, 100]
Second Element: 90

In [13]:
# Create a list
my_list = [10, 20, 30, 40, 70]

# Print the original list
print("Original List:", my_list)

# Reverse the list
my_list.reverse()

# Print the reversed list
print("Reversed List:", my_list)

Original List: [10, 20, 30, 40, 70]
Reversed List: [70, 40, 30, 20, 10]

In [40]:
# Create a tuple
my_tuple = (100, 200, 300)

# Print the tuple
print(my_tuple)

(100, 200, 300)

In [39]:
# Create a tuple
my_tuple = ('red', 'green', 'blue', 'yellow')

# Access the second-to-last element
second_last_element = my_tuple[-2]

# Print the second-to-last element
print(second_last_element)

blue

In [38]:
# Create a tuple
my_tuple = (10, 20, 5, 15)

# Find the minimum number
min_number = min(my_tuple)

# Print the minimum number
print(min_number)

5

In [37]:
# Create a tuple
my_tuple = ('dog', 'cat', 'rabbit')

# Find the index of the element "cat"
index = my_tuple.index('cat')

# Print the index
print(index)

1

In [36]:
# Create a tuple containing three different fruits
fruits = ('apple', 'banana', 'orange')

# Check if "kiwi" is in the tuple
if 'kiwi' in fruits:
    print("Kiwi is in the tuple.")
else:
    print("Kiwi is not in the tuple.")

Kiwi is not in the tuple.

In [35]:
# Create a set with the elements 'a', 'b', 'c'
my_set = {'a', 'b', 'c'}

# Print the set
print(my_set)

{'b', 'c', 'a'}

In [34]:
# Create a set
my_set = {1, 2, 3, 4, 5}

# Print the original set
print("Original Set:", my_set)

# Clear the set
my_set.clear()

# Print the cleared set
print("Cleared Set:", my_set)

Original Set: {1, 2, 3, 4, 5}
Cleared Set: set()

In [33]:
# Create a set
my_set = {1, 2, 3, 4}

# Print the original set
print("Original Set:", my_set)

# Remove the element 4 from the set
my_set.discard(4)

# Print the updated set
print("Updated Set:", my_set)

Original Set: {1, 2, 3, 4}
Updated Set: {1, 2, 3}

In [31]:
set1 = {1, 2, 3}
set2 = {3, 4, 5}

# Print the original sets
print("Set 1:", set1)
print("Set 2:", set2)

# Find the union of the two sets
union_set = set1.union(set2)

# Print the union set
print("Union Set:", union_set)

Set 1: {1, 2, 3}
Set 2: {3, 4, 5}
Union Set: {1, 2, 3, 4, 5}

In [30]:
# Create two sets
set1 = {1, 2, 3}
set2 = {2, 3, 4}

# Print the original sets
print("Set 1:", set1)
print("Set 2:", set2)

# Find the intersection of the two sets
intersection_set = set1.intersection(set2)

# Print the intersection set
print("Intersection Set:", intersection_set)

Set 1: {1, 2, 3}
Set 2: {2, 3, 4}
Intersection Set: {2, 3}

In [42]:
# Create a dictionary
person = {
    "name": "John Doe",
    "age": 25,
    "city": "New York"
}

# Print the dictionary
print("Dictionary:", person)

# Access and print individual values
print("Name:", person["name"])
print("Age:", person["age"])
print("City:", person["city"])

Dictionary: {'name': 'John Doe', 'age': 25, 'city': 'New York'}
Name: John Doe
Age: 25
City: New York

In [27]:
# Create a dictionary
person = {
    'name': 'John',
    'age': 25
}

# Print the original dictionary
print("Original Dictionary:", person)

# Add a new key-value pair
person['country'] = 'USA'

# Print the updated dictionary
print("Updated Dictionary:", person)

Original Dictionary: {'name': 'John', 'age': 25}
Updated Dictionary: {'name': 'John', 'age': 25, 'country': 'USA'}

In [26]:
# Create a dictionary
person = {
    'name': 'Alice',
    'age': 30
}

# Access the value associated with the key "name"
name = person['name']

# Print the value
print("Name:", name)

Name: Alice

In [24]:
# Create a dictionary
person = {
    'name': 'Bob',
    'age': 22,
    'city': 'New York'
}

# Print the original dictionary
print("Original Dictionary:", person)

# Remove the key "age"
del person['age']

# Print the updated dictionary
print("Updated Dictionary:", person)

Original Dictionary: {'name': 'Bob', 'age': 22, 'city': 'New York'}
Updated Dictionary: {'name': 'Bob', 'city': 'New York'}

In [25]:
# Create a dictionary
person = {
    'name': 'Alice',
    'city': 'Paris'
}

# Check if the key "city" exists
if 'city' in person:
    print("The key 'city' exists in the dictionary.")
else:
    print("The key 'city' does not exist in the dictionary.")

The key 'city' exists in the dictionary.

In [41]:
# Create a list
my_list = [1, 2, 3, 4, 5]

# Create a tuple
my_tuple = ('apple', 'banana', 'cherry')

# Create a dictionary
my_dict = {'name': 'John', 'age': 30, 'city': 'New York'}

# Print the list, tuple, and dictionary
print("List:", my_list)
print("Tuple:", my_tuple)
print("Dictionary:", my_dict)

List: [1, 2, 3, 4, 5]
Tuple: ('apple', 'banana', 'cherry')
Dictionary: {'name': 'John', 'age': 30, 'city': 'New York'}

In [19]:
import random

# Create a list of 5 random numbers between 1 and 100
random_list = random.sample(range(1, 101), 5)

# Print the original list
print("Original List:", random_list)

# Sort the list in ascending order
random_list.sort()

# Print the sorted list
print("Sorted List:", random_list)

Original List: [91, 98, 39, 74, 54]
Sorted List: [39, 54, 74, 91, 98]

In [17]:
# Create a list with strings
fruit_list = ["apple", "banana", "peach", "date", "elderberry, Tomato"]

# Print the list
print("Fruit List:", fruit_list)

# Print the element at the third index
print("Fruit at third index:", fruit_list[2])

Fruit List: ['apple', 'banana', 'peach', 'date', 'elderberry, Tomato']
Fruit at third index: peach

In [15]:
# Create two dictionaries
dict1 = {'a': 1, 'b': 2}
dict2 = {'c': 3, 'd': 4}

# Print the original dictionaries
print("Dictionary 1:", dict1)
print("Dictionary 2:", dict2)

# Combine the two dictionaries
combined_dict = {**dict1, **dict2}

# Print the combined dictionary
print("Combined Dictionary:", combined_dict)

Dictionary 1: {'a': 1, 'b': 2}
Dictionary 2: {'c': 3, 'd': 4}
Combined Dictionary: {'a': 1, 'b': 2, 'c': 3, 'd': 4}

In [14]:
# Create a list of strings
string_list = ["apple", "banana", "apple", "cherry", "banana"]

# Print the original list
print("Original List:", string_list)

# Convert the list to a set
string_set = set(string_list)

# Print the resulting set
print("Resulting Set:", string_set)

Original List: ['apple', 'banana', 'apple', 'cherry', 'banana']
Resulting Set: {'banana', 'apple', 'cherry'}